name: Mono Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - run: npm ci

      - name: lint application
        run: npm run lint

      - name: build application
        run: npm run build

      - uses: azure/webapps-deploy@v3
        with:
          package: "./dist"
          app-name: "asc-mono-app-dev"
          publish-profile: ${{ secrets.mono_dev }}
